name: Windows vcpkg Workflow

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
  # Execute a "nightly" build at 2 AM UTC 
  - cron:  '0 2 * * *'

jobs:
  build:
    name: 'Windows vcpkg job'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    # Restore from cache the previously built ports. If "cache miss"
    # then provision vcpkg, install desired ports, finally cache everything for the next run.
    - name: Restore from cache and run vcpkg
      uses: lukka/run-vcpkg@v3
      with:
        vcpkgArguments: '--triplet x64-windows boost-asio boost-smart-ptr protobuf'
        # commit from vcpkg's master branch on 2020/06/01
        vcpkgGitCommitId: 6d36e2a86baf8d227fc6dce587bd69997d67fb5e
        # Workaround for https://github.com/ros-industrial/abb_libegm/pull/101#discussion_r433370614
        # This line can be removed once protobuf is  linked via its imported CMake targets
        vcpkgDirectory: '${{ github.workspace }}/../vcpkg'  

    - name: Configure the project 
      shell: bash
      run: | 
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake ..
        cmake --build . --config RelWithDebInfo
        cmake --install . --config RelWithDebInfo
